### ISSUE TITLE
Partially_posted

### ISSUE THREAD

**Issue by dinaatomy** [ralfeus/order#38]
Прошу сделать для удобства и экономии времени, особенно когда выкупается огромное количество товара, функцию при нажатии на статус partially_posted которой выводило бы сообщение о невыкупленном товаре - код, наименование, количество.

**Comment by ralfeus** [comment]
Статус заказаного товара можно проверить в списке заказаных товаров (https://dina.talya.kim/admin/orders/products)
![image](https://user-images.githubusercontent.com/1980527/100525886-22ac4b80-31c4-11eb-8970-c683e6a339ac.png)

Точно нужно то же самое показывать в РО?

**Comment by dinaatomy** [comment]
речь шла о том чтобы быстро увидеть не выкупленный товар при нажатии на
статус partially_posted, для быстрого определения товара. было бы очень
удобно, конечно если это возможно и не сложно

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 29 нояб. 2020 г. в 05:53, ralfeus <notifications@github.com>:
