### ISSUE TITLE
инвойс коненчный блакн 

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#40]
чтобы выходил вычет с баланса, либо инвойс конечный- в виде бланка как поменялась сумма, видна была. 
 чтобы  могли видеть по азказу что ушло.
либо сделать транзикцию как мы реализовали в прошлом нашем сайте.

**Comment by ralfeus** [comment]
Створювати sale invoice після створення РО з кінцевою сумою замовлення (після видалення недоступних товарів)
