### ISSUE TITLE
Фільтрація замовлень (sale orders)

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#48]
удобная фильтрация.
расширенная фильтрация чтобы выбрать нужные заказ по дате, по статусу, по  по спосбоы оптравке. 
 и несколько параметров задавать

**Comment by ralfeus** [comment]
Уточни поля, за якими фільтрувати:
- дата (створення? коли має бути замовлено?)
- статус
- спосіб відправки

Ще щось?
