### ISSUE TITLE
Реалізувати пошук

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#57]
в админке хорошо не поиск а выборка  
 как это было реализовано у нас на мумидэ 
  типа ткого 
![2021-01-19_031415](https://user-images.githubusercontent.com/73013277/104954461-9ff97d00-5a0b-11eb-9255-3c7930d622b4.jpg)
то есть выборка для стутсов, для имен может поиск быть 
И такое в меню  ордер . и меню товаров и меню в оплатах, потому что 
 нужно к примеру сделать поиск 
  все оплаты которые и пендинг и апровед
   а не получается 
    или в заказъ выборку все товары котоыре  кен бы пейд  и шиппед 
     иил одну, или все кроме одного статуса

**Comment by ralfeus** [comment]
- Замовлення
- Платежі
- Замовлені товари
