### ISSUE TITLE
Забезпечити унікальність кодів товарів з врахуванням нулів на початку

### ISSUE THREAD

**Issue by ralfeus** [ralfeus/order#66]

**Comment by moomidae** [comment]
Миша насчет кодов. 
У нас есть те товары, которые просят без коробки отправлять, чтоы сделать чуть дешевле по пересылке. 
Например хемохим код 1 
а раньше без коробки мы пропсиывали прям в названи  1 -1   или может как-то назвать b1 
 чтобы проармма считывала его как код 1 т выкупала а при подсчете и арспечатке  считалось как без коробки.
