### ISSUE TITLE
orders product

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#69]
в личте чтобі появлялись только те заказі которіе po created
    или отделить статусами

**Comment by ralfeus** [comment]
А що заважає просто фільтрувати за статусом?

**Comment by ralfeus** [comment]
> 
> 
> в личте чтобі появлялись только те заказі которіе po created
> или отделить статусами

А що заважає просто фільтрувати за статусом?

**Comment by ralfeus** [comment]
Фільтр за po_created встановлено за умовчанням

**Comment by moomidae** [comment]
И как мне там найти товары которые находятся в заказе, еоторый запускался
в created  но при этом они пендинг. Чтобы поставить их как выкупленнве или
unavaible

пт, 29 янв. 2021 г., 8:00 PM ralfeus <notifications@github.com>:

**Comment by ralfeus** [comment]
Фільтрація за ID замовлення? Чи ти хочеш бачити всі замовлення в po_created?

**Comment by ralfeus** [comment]
Додано фільтрування ОР за статусом замовлення
