### ISSUE TITLE
каталог

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#70]
всплывающее окно- каталог

**Comment by ralfeus** [comment]
Більше деталей, будь ласка

**Comment by moomidae** [comment]
каталог описание товара ,  и привязка с атоми сайтом, чтобы  видели есть продукция или нет описание на русском чобы могла иметь , ну и код.. 
 
 например  
![2021-04-10_120653](https://user-images.githubusercontent.com/73013277/114256657-ccfb7180-99f5-11eb-9c2b-01311955a544.jpg)
єто позже после пересылок можно сделать
