### ISSUE TITLE
Додати доставку в інвойс

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#72]
инвойс   если есть отмечать пеерсылку. 
 отмечать фирму

**Comment by moomidae** [comment]
кстати пеерсылка не выходит 
 А еще фирму мне надо 
 если на михва првлиьно 
  если на мунгема то там поменять 
   KIM MOON GYEOM 
    компания:
MOOMIDAE

**Comment by ralfeus** [comment]
А якщо інвойс робиться для декількох замовлень, вказувати сумарну вартість доставки?
