### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#76]
В ппейменте  мне надо чтобы сумму прихода  отмеченная можно по периодам смотреть 
 то есть например сколько было с 1 январа по 1 февраля. иил с 1 января по 1 апреля.... 
 Чтобы можно было проверить статистику оплачено 
 суммы которыее режекстед  не учитывались

**Comment by ralfeus** [comment]
Аналітика вирішується окремою ВІ службою
