### ISSUE TITLE
распечатка заказа

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#78]
- [x] Распечатка заказа - больше шрифт 
- [x] На распечатке должен показываться вес товара, 
При оформлении заказа 
- [x]  телефон обязательное поле 
- [x]  Имя получателя обязательно 
- [x]   индекс обязательно 
- [x]    Для дчл  написание получателя , адреса, телефона  на англйиском. 
- [x]  статусы товаровов на тот момент 
- [ ]    Отметка предзааказа  красным цветом чтобы сразу видели что предзаказ

**Comment by ralfeus** [comment]
> Отметка предзааказа красным цветом чтобы сразу видели что предзаказ

Позначення де? У списку замовлень?

**Comment by moomidae** [comment]
Шрифт самих товаров.  Потмоу что когад упаковывает надо првоериять товары.ю какие именно товары, очен мелко ,  надо сделать большое чтобы хорошо видно было

**Comment by moomidae** [comment]
вес  товара 
 я вижу уже пояявилась  
спасибо

**Comment by moomidae** [comment]
общая цена  заказа  с пересылкой и без нужно еще 
 просто по цене мы опеределяем кк цоенить посылку и какой подарко можно положить

**Comment by moomidae** [comment]
про статусы это наверно не в арспечатке.
 перейду  в другое задание

**Comment by ralfeus** [comment]
> > Отметка предзааказа красным цветом чтобы сразу видели что предзаказ
> 
> Позначення де? У списку замовлень?

Що з цим?

**Comment by moomidae** [comment]
у тебя есь предакза когда пишется но они его не замечают почему-то 
 поєтмоу краснім может обохначитьчтобі видели

**Comment by ralfeus** [comment]
> 
> 
> у тебя есь предакза ( тот коотры postpone)
> когда пишется но они его не замечают почему-то
> поєтмоу красным может обозначитьчтобі видели

Позначити де? Хто має це бачити?

**Comment by ralfeus** [comment]
Можна апдейт? Чи можна вже закривати?

**Comment by ralfeus** [comment]
> 
> 
> > у тебя есь предакза ( тот коотры postpone)
> > когда пишется но они его не замечают почему-то
> > поєтмоу красным может обозначитьчтобі видели
> 
> Позначити де? Хто має це бачити?

Нема новин. Закриваю
