### ISSUE TITLE
в orders   сразу было видно каким числом выкуплен заказ

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#80]
в общем меню, чтобы не бегать постоянно в  purchase order  , сразу можно было каокй заказ когда выкупили и какой  надо уже собирать.  И чтобы  можно было  сделать фильтрацию по выкупу

**Comment by ralfeus** [comment]
В одному замовленні як правило декілька РО. З яким пов'язувати? Першим чи останнім?
