### ISSUE TITLE
Вказувати відсутність коробки для товарів у замовленні

### ISSUE THREAD

**Issue by ralfeus** [ralfeus/order#82]
Миша насчет кодов. 
У нас есть те товары, которые просят без коробки отправлять, чтоы сделать чуть дешевле по пересылке. 
Например хемохим код 1 
а раньше без коробки мы пропсиывали прям в названи  1 -1   или может как-то назвать b1 
 чтобы проармма считывала его как код 1 т выкупала а при подсчете и арспечатке  считалось как без коробки.

_Originally posted by @moomidae in https://github.com/ralfeus/order/issues/66#issuecomment-787399484_

**Comment by ralfeus** [comment]
Потребую більше деталей.
- Що значить "без коробки"? Все замовлення без коробки?
- Чи всі товари можна так замовляти? Якщо не всі, то як визначити, які можна?

**Comment by moomidae** [comment]
коробка имеется ввиду  
 к прмиеру хемохим 1 коробка, приходит в нее упаковано 6 небольших коробок и в небольшие коробочки 10пачек. 
  Вот иногда кто для себя берет не хочет эти коробки , плтить за вес.  просит без коробок сделать.

**Comment by ralfeus** [comment]
Найкращий варіант - створити окремий товар з меншою вагою і відповідним описом. Я не бачу великої користі від можливості поставити один чекбокс до товару замість вибору іншого товару. Роботи ж при цьому на це витратиться чимало.
