### ISSUE TITLE
учет склада

### ISSUE THREAD

**Issue by moomidae** [ralfeus/order#93]
нужен учет склада того что есть на полках и если отмечаем , что берется, также учитывалось

**Comment by ralfeus** [comment]
Де ти це хочеш бачити?

**Comment by ralfeus** [comment]
1. Складський облік є окремою підсистемою
2. Один склад є локальним (в Кореї)
3. Кожний виконаний РО збільшує кількість товарів на локальному складі
4. Кожний виконаний SO зменшує кількість товарів на локальному складі
5. SO має властивість "quick". При його позначенні РО створюється, але товари відправляються зі складу (якщо всі товари на складі є)
